### ISSUE TITLE
Add route level enabling of session cookies

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-api#112]
When a route is provisioned on Openshift where an HAProxy is used, there are annotations that can be set to change the behaviour of the HAProxy.  The `gwa-kube-api` defines two templates and a namespace parameter `template-version` determines whether version `v1` with a session cookie is used, or `v2` with session cookie disabled.

The problem is that this is at a namespace level and there are cases where only one route in the namespace needs the session cookie.  So a new tag on the `route` will be introduced that will get passed to the `gwa-kube-api` and used in determining which template to use.

Example:

```yaml
services:
- name: my-service
  routes:
  - name: my-route
    tags: [ ns.NS, aps.route.session.cookie.enabled ]

```
