### ISSUE TITLE
support for custom annotations on routes creates with kube api

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-api#118]
The `kube-api` is responsible for any custom provisioning based on the infrastructure that Kong data planes are deployed to.  For BC Government Emerald Openshift cluster, there is a requirement to annotation the DataClass based on the sensitivity of the data being passed through the endpoint.

This ticket is the work on the `kube-api` to provide a way of specifying a DataClass on a Kong Route and then have the appropriate annotation be applied on the `Route` resource in Openshift.

**Comment by ikethecoder** [comment]
Similar to how #112 worked, have a custom annotation that will specify the desired DataClass:

```
services:
- name: my-service
  routes:
  - name: my-route
    tags: [ ns.NS, aps.route.dataclass.medium ]
```

With valid values: `aps.route.dataclass=low` `aps.route.dataclass=medium` and `aps.route.dataclass=high`

The `kube-api` will then use the information to add the appropriate annotation on the Route.
