### ISSUE TITLE
Enhance gateway status to use the Kube api to check the upstream and to include the assigned IP

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-api#133]
**Background:**

Some data planes may be on Openshift clusters that use VMware NSX Advanced Load Balancer (AVI Kubernetes Operator), which is an advanced ingress controller.  In this case, the `kube-api` will provision an Openshift Route and an IP address will be dynamically assigned.  We want the IP address to be available when a user calls the `/v2/namespaces/<string:namespace>/services` endpoint.

**A/C:**

- move the status logic from `gatewayApi` to `kubeApi`
- have the `gatewayApi` call the `kubeApi` to get the status data
- update the `kubeApi` to enrich the status data with the IP address if it is available

**Technical notes:**

IP address can be found in the Route detail, if the AVI operator is used on the cluster:

```yaml
status:
  ingress:
    - host: <SERVICE>.api.gov.bc.ca
      routerName: ako-OCPEMERALD
      conditions:
        - type: Admitted
          status: 'True'
          message: 10.99.10.8
```
