### ISSUE TITLE
Gateway configuration with _format_version being rejected

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-api#73]
**Steps**

- In a new namespace, make a yaml file that has _format_version included in it:

```
_format_version: "1.1"
services:
- name: temp-service
  tags: [ ns.$NS ]
  routes: []
```

- Run: `gwa pg`

**Expected Results**

- The service is created successfully

**Actual Results**

The following error is returned:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/23747270/205222241-62f34998-1fae-4d8c-b9a8-464dee5139cb.png">
